version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/test

hooks:

   AfterInstall:
    - location: deploy-scripts/start-docker.sh
      runas: ec2-user
  
  ApplicationStop:
    - location: deploy-scripts/stop-docker.sh
      runas: ec2-user