version: 0.1
os: linux
files:
   - source: /
     destination: /home/ec2-user/test

hooks:
   AfterInstall:
    - location: deploy-scripts/start-docker.sh
      runas: root
  
   ApplicationStop:
    - location: deploy-scripts/stop-docker.sh
      runas: root
