php:
  build: ./docker-build/php
  #image: php:7-fpm
  volumes:
    - ./html:/html
  links:
    - mysql
  env_file:
    - ./env/php.env

node:
  build: ./docker-build/node
  volumes:
    - ./app:/app
  ports:
  - "8080:8080"

web:
  image: nginx:latest
  ports:
  - "80:80"
  volumes:
  - ./html:/html
  - ./site.conf:/etc/nginx/conf.d/site.conf
  - ./default.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

mysql:
  image: mariadb
  env_file:
    - ./env/mysql.env

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql
  ports:
    - 8183:80
  env_file:
    - ./env/phpmyadmin.env
